// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolidDry.Infrastructure.Persistence;

#nullable disable

namespace SolidDry.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SolidDryDbContext))]
    [Migration("20260228035838_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SolidDry.Core.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CodeSubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeSubmissionId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.CodeSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodeSubmissions");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CodeSubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Principle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeSubmissionId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.QaAdjudication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalibrationTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalLabel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QaReviewerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FindingId");

                    b.ToTable("QaAdjudications");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.ReviewDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Label")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FindingId");

                    b.ToTable("ReviewDecisions");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.VendorProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecisionScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReworkRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SlaComplianceRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TasksReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VendorProfiles");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.AuditEvent", b =>
                {
                    b.HasOne("SolidDry.Core.Entities.CodeSubmission", "CodeSubmission")
                        .WithMany("AuditEvents")
                        .HasForeignKey("CodeSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CodeSubmission");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.Finding", b =>
                {
                    b.HasOne("SolidDry.Core.Entities.CodeSubmission", "CodeSubmission")
                        .WithMany("Findings")
                        .HasForeignKey("CodeSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeSubmission");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.QaAdjudication", b =>
                {
                    b.HasOne("SolidDry.Core.Entities.Finding", "Finding")
                        .WithMany("QaAdjudications")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.ReviewDecision", b =>
                {
                    b.HasOne("SolidDry.Core.Entities.Finding", "Finding")
                        .WithMany("ReviewDecisions")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.CodeSubmission", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Findings");
                });

            modelBuilder.Entity("SolidDry.Core.Entities.Finding", b =>
                {
                    b.Navigation("QaAdjudications");

                    b.Navigation("ReviewDecisions");
                });
#pragma warning restore 612, 618
        }
    }
}
